apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: registry.gitlab.com/distributed-mald/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com