apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
spec:
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: registry.gitlab.com/distributed-mald/website:${CI_COMMIT_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 30
        env:
        - name: JAVA_OPTIONS
          value : '-Xmx100m'
        - name: SPRING_PROFILES_ACTIVE
          value : 'production'
      imagePullSecrets:
        - name: registry.gitlab.com