apiVersion: v1
data:
# LetsEnrypt fullchain.pem + privkey.pem respectively, both base64 encoded
  tls.cert: xxx
  tls.key: xxx
kind: Secret
metadata:
  name: mald-tls-secret
  namespace: default
type: Opaque
