# created using: kubectl create secret docker-registry mald-gitlab-registry-secret --docker-server=registry.gitlab.com --docker-username=gitlab-ci-token --docker-password=<gitlab personal access token> --docker-email=<your gitlab email>
apiVersion: v1
data:
  .dockercfg: xxx
kind: Secret
metadata:
  name: registry.gitlab.com
type: kubernetes.io/dockercfg
