apiVersion: v1
kind: Secret
metadata:
  name: mald-tls-secret
data:
  tls.crt: base64 encoded crt - cat fullchain.pem | base64 -w 0
  tls.key: base64 encoded key - cat privkey.pem | base64 -w 0
type: Opaque